name: Default environment vairable
on: push
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - run: echo "The name of the workflow $GITHUB_WORKFLOW"
      - run: echo "A unique number for each run within a repository $GITHUB_RUN_ID"
      - run: echo "A unique number for each run of a particular workflow in a repository $GITHUB_RUN_NUMBER"
      - run: echo "The job_id of the current job $GITHUB_JOB"
      - run: echo "The unique identifier (id) of the action $GITHUB_ACTION"
      - run: echo "The path where your action is located $GITHUB_ACTION_PATH"
      - run: echo "Always set to true when GitHub Actions is running the workflow $GITHUB_ACTION"
      - run: echo "$GITHUB_ACTOR"
      - run: echo "$GITHUB_REPOSITORY"
      - run: echo "$GITHUB_EVENT_NAME"
      - run: echo "$GITHUB_EVENT_PATH"
      - run: echo "$GITHUB_WORKSPACE"
      - run: echo "The commit SHA that triggered the workflow $GITHUB_SHA"
      - run: echo "The operating system of the runner executing the job $RUNNER_OS"
      - run: echo "The path to a temporary directory on the runner $RUNNER_TEMP"
     
